instructions: |
  Your primary task is to determine whether the given text contains a section that provides a chronological background of a merger. 
  This section may be titled differently, such as 'Background of the Transaction,' 'Background of the Acquisition,' 'Background of the Offer,' or 'Background of the Consolidation,' and so on. 
  Carefully scan the document to check if such a section exists. 
  Do not analyze the contents—only confirm whether the section is present. 
  If the section is found, return [Found]. If not, return [Not Found].

query: |
  Locate the 'Background of the Merger' section (which may be titled differently, such as 
  'Background of the Transaction', 'Background of the Acquisition', 'Background of the Consolidation', or 'Background of the Offer'). 
  This section provides a chronological timeline of events leading to the merger. 
  For example, the timeline will describe events like: On date X, company A met with company B. 
  If and only if you find this section, strictly return [Found]. 
  If you cannot find the section, strictly return [Not Found]. Do not return anything else.
